// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqkwqdjrfujqfxihcqlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxa3dxZGpyZnVqcWZ4aWhjcWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjgxMzAsImV4cCI6MjA3MzkwNDEzMH0.9UcE-bnk3x2OC7VofFHgeC1kK6hT_0x6OjsEWF1sAj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});